name: casa_oscar
description: Casa Oscar Smart Home v0.2
publish_to: 'none'
version: 0.2.0+2
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: any
  google_fonts: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
flutter:
  uses-material-design: true
